words = [
    "Neovim",
    "Neovim's",
    "angular",
    "asm68k",
    "autocmd",
    "autocmds",
    "autocommands",
    "automake",
    "bash",
    "bib",
    "bibtex",
    "birb",
    "bzl",
    "clientscript",
    "commonlisp",
    "config",
    "confini",
    "cook",
    "cooklang",
    "cs",
    "csharp",
    "devicetree",
    "diff",
    "dosini",
    "dsp",
    "dts",
    "ecma",
    "ecmascript",
    "eelixir",
    "eex",
    "elixir",
    "embedded",
    "erl",
    "erlang",
    "eruby",
    "ex",
    "expect",
    "facility",
    "faust",
    "filter",
    "foldexpr",
    "foldlevelstart",
    "foldmethod",
    "fsd",
    "gdresource",
    "gdshader",
    "gdshaderinc",
    "git",
    "gitconfig",
    "gitdiff",
    "gitrebase",
    "glimmer",
    "godot",
    "gyp",
    "handlebars",
    "haskell",
    "haskellpersistent",
    "hs",
    "html",
    "htmlangular",
    "idris",
    "idris2",
    "ini",
    "interface",
    "janet",
    "javascript",
    "javascriptreact",
    "jproperties",
    "js",
    "json",
    "jsonc",
    "jsx",
    "latex",
    "ld",
    "linkerscript",
    "lisp",
    "m68k",
    "make",
    "markdown",
    "muttrc",
    "mysqp",
    "neomuttrc",
    "noplugin",
    "nvim",
    "ocaml",
    "ocamlinterface",
    "pandoc",
    "patrickswijgman",
    "pbtxt",
    "pcall",
    "perl",
    "persistent",
    "pl",
    "poe",
    "poefilter",
    "powershell",
    "properties",
    "ps1",
    "py",
    "python",
    "qml",
    "qmljs",
    "rebase",
    "resource",
    "rtp",
    "runescript",
    "runtimepath",
    "sbt",
    "scala",
    "sface",
    "sh",
    "shaderslang",
    "sharp",
    "simple",
    "slang",
    "sqp",
    "ssh",
    "sshconfig",
    "starlark",
    "surface",
    "svg",
    "systemverilog",
    "t32",
    "tal",
    "tape",
    "tcl",
    "template",
    "terraform",
    "tex",
    "textproto",
    "tla",
    "tlaplus",
    "trace32",
    "treesitter",
    "treesitters",
    "ts",
    "tsx",
    "typ",
    "typescript",
    "typescriptreact",
    "typst",
    "udev",
    "udevrules",
    "uxn",
    "uxntal",
    "vars",
    "verilog",
    "vhs",
    "vlang",
    "xdefaults",
    "xml",
    "xresources",
    "xsd",
    "xslt",
]
